/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-27 02:36:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\">\n");
      out.write("        <title> MWLC GROUP </title>\n");
      out.write("        <link rel=\"shortcut icon\"  href=\"presentacion/imagenes/icono.ico\"/>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"presentacion/css/principal.css\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class= \"pagina\">\n");
      out.write("                        \n");
      out.write("            <div class=\"header\">\n");
      out.write("                <div class=\"logo\">\n");
      out.write("                    <img src=\"presentacion/imagenes/lgo3.png\" width=\"10%\">\n");
      out.write("                </div>\n");
      out.write("                <img src=\"presentacion/imagenes/header.jpg\" width=\"100%\">\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"login-box\">\n");
      out.write("                <h1>Inicio de sesión</h1>\n");
      out.write("                <form method=\"post\" name=\"formulario\" action=\"control/validar.jsp\">\n");
      out.write("                    <table>\n");
      out.write("                        <tr><th>Usuario</th><th><input type=\"text\" name=\"usuario\" required></th></tr>\n");
      out.write("                        <tr><th>clave</th><th><input type=\"password\" name=\"clave\" required></th></tr>\n");
      out.write("                        <tr><th><input type=\"submit\" value=\"Ingresar\"></th><th><input type=\"submit\" value=\"Cancelar\"></th></tr>\n");
      out.write("                    </table> \n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"contenido\">\n");
      out.write("                <h1>BIENVENIDO</h1>\n");
      out.write("                <p>  Si lo que estás buscando es un pagina web potente y de fácil manejo  en el sector de la administración de fincas,\n");
      out.write("                     entonces nos has encontrado.Podemos ayudarte en la gestión de la contabilidad para su finca.\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("                <p align=\"center\">\n");
      out.write("                    <img src=\"presentacion/imagenes/mwlc.jpg\" width=\"50%\">\n");
      out.write("                </p>\n");
      out.write("                <p> En Colombia, el sector agro es uno de los principales ejes que mueve el país, es por eso que en MWLC GROUP pensamos en ti y lo mejor para administrar tu finca. \n");
      out.write("                    Y es que nuestro país, según la FAO (Organización de las Naciones Unidas para la Alimentación y la Agricultura), puede convertirse en una de las grandes despensas del mundo, \n");
      out.write("                    pues es uno de los siete países en Latinoamérica con mayor potencial para el desarrollo de áreas cultivables: “Entre 223 países en los que se evaluó el potencial de expansión \n");
      out.write("                    del área agrícola –sin afectar el área del bosque natural– esta nación ocupó el puesto 25, ya que de las 22 millones de hectáreas cultivables, solo están sembradas 4,8, sin \n");
      out.write("                    incluir el potencial de la Altillanura, estimado en 3,5 millones de hectáreas” \n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"footer\">\n");
      out.write("                <address align=\"center\">&copy; Todos los Derechos reservados - Desarrollado por el GRUPO MWLC </address>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
