/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-10-25 19:07:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.presentacion.parqueo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import clases.Parqueo;
import java.util.ArrayList;
import clases.Parqueadero;
import clases.Persona;

public final class parqueo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("clases.Parqueo");
    _jspx_imports_classes.add("clases.Persona");
    _jspx_imports_classes.add("clases.Parqueadero");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession sesion = request.getSession();
    Persona USUARIO = null;
    if(sesion.getAttribute("usuario")==null) response.sendRedirect("../index.jsp?error=2");
    else USUARIO = (Persona) sesion.getAttribute("usuario");
    String filtro="identificacionAdministrador='"+USUARIO.getIdentificacion()+"'";
    Parqueadero parqueadero = Parqueadero.getListaEnObjetos(filtro).get(0); 
    
    filtro="";
    String placa="";
    String cPlaca="";
    if(request.getParameter("cPlaca")!=null){
        placa=request.getParameter("placa");
        cPlaca="checked";
        filtro="placa like'%"+ placa +"%'";
    }
    
    String ingresoInicial="";
    String ingresoFinal="";
    String cIngreso="";
    if(request.getParameter("cIngreso")!=null && !request.getParameter("ingresoInicial").trim().equals("") && !request.getParameter("ingresoFinal").trim().equals("")){
        ingresoInicial = request.getParameter("ingresoInicial");
        ingresoFinal = request.getParameter("ingresoFinal");
        cIngreso="checked";
        if(!filtro.equals("")) filtro+=" and ";
        filtro+="fechaHoraIngreso between '"+ ingresoInicial +"' and '"+ ingresoFinal +"'";
    }
    
    String salidaInicial="";
    String salidaFinal="";
    String cSalida="";
    if(request.getParameter("cSalida")!=null && !request.getParameter("salidaInicial").trim().equals("") && !request.getParameter("salidaFinal").trim().equals("")){
        salidaInicial = request.getParameter("salidaInicial");
        salidaFinal = request.getParameter("salidaFinal");
        cSalida="checked";
        if(!filtro.equals("")) filtro+=" and ";
        filtro+="fechaHoraSalida between '"+ salidaInicial +"' and '"+ salidaFinal +"'";
    }
    
    String identificacion="";
    String cIdentificacion="";
    if(request.getParameter("cIdentificacion")!=null){
        identificacion=request.getParameter("identificacion");
        cIdentificacion="checked";
        if(!filtro.equals("")) filtro+=" and ";
        filtro+="identificacionCliente like'%"+ identificacion +"%'";
    }
    
    String cDentroDeParqueadero="";
    if(request.getParameter("cDentroDeParqueadero")!=null){
        cDentroDeParqueadero="checked";
        if(!filtro.equals("")) filtro+=" and ";
        filtro+="fechaHoraSalida is null";
    }
    
    
    String lista="";
    if(!filtro.equals("")) filtro+=" and ";
    filtro+="idParqueadero="+parqueadero.getId();
    ArrayList<Parqueo> datos = Parqueo.getListaEnObjetos(filtro);
    for (int i = 0; i < datos.size(); i++) {
            Parqueo parqueo = datos.get(i);
            lista+="<tr>";
            lista+="<td>"+ parqueo.getFechaHoraIngreso()+"</td>";
            lista+="<td>"+ parqueo.getFechaHoraSalida()+"</td>";
            lista+="<td>"+ parqueo.getPlaca()+"</td>";
            lista+="<td>"+ parqueo.getIdentificacionCliente()+" "+parqueo.getCliente()+"</td>";
            lista+="<td>"+ parqueo.getCodigoDeBarras()+"</td>";
            lista+="<td>";
            if(parqueo.getFechaHoraSalida().equals("")) {
                if (parqueadero.getModoDeControl()=='T' && parqueo.getCodigoDeBarras().equals("")) lista+="<a href='parqueo/ticket.jsp?id=" + parqueo.getId() + "' target='_blank'>T</<>";//tiquets
                lista+="<a href='principal.jsp?CONTENIDO=parqueo/salidaVehiculo.jsp&idParqueadero="+ parqueadero.getId() +"&id="+ parqueo.getId() +"' title='Salir'>S</a>";
            }
            lista+="</td>";
            lista+="</tr>";
        }

      out.write("\n");
      out.write("\n");
      out.write("<h3>LIBRO DE PARQUEO PARA EL PARQUEADERO ");
      out.print(parqueadero.getNombre().toUpperCase() );
      out.write("</h3>\n");
      out.write("<form name=\"formulario\" method=\"post\">\n");
      out.write("    <table>\n");
      out.write("        <tr><th><input type=\"checkbox\" name=\"cPlaca\" ");
      out.print(cPlaca);
      out.write(">Placa</th><td><input type=\"text\" name=\"placa\" value=\"");
      out.print(placa);
      out.write("\" maxlength=\"7\"></td></tr>\n");
      out.write("        <tr>\n");
      out.write("            <th><input type=\"checkbox\" name=\"cIngreso\" ");
      out.print(cIngreso);
      out.write(">Ingreso</th>\n");
      out.write("            <td>Desde<input type=\"datetime\" name=\"ingresoInicial\" value=\"");
      out.print(ingresoInicial);
      out.write("\">Hasta<input type=\"datetime\" name=\"ingresoFinal\" value=\"");
      out.print(ingresoFinal);
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <th><input type=\"checkbox\" name=\"cSalida\" ");
      out.print(cSalida);
      out.write(">Salida</th>\n");
      out.write("            <td>Desde<input type=\"datetime\" name=\"salidaInicial\" value=\"");
      out.print(salidaInicial);
      out.write("\">Hasta<input type=\"datetime\" name=\"salidaFinal\" value=\"");
      out.print(salidaFinal);
      out.write("\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr><th><input type=\"checkbox\" name=\"cIdentificacion\" ");
      out.print(cIdentificacion);
      out.write(">Identificacion cliente</th><td><input type=\"text\" name=\"identificacion\" value=\"");
      out.print(identificacion);
      out.write("\" maxlength=\"15\"></td></tr>\n");
      out.write("        <tr><th><input type=\"checkbox\" name=\"cDentroDeParqueadero\" ");
      out.print(cDentroDeParqueadero);
      out.write(">Dentro de parqueadero</th></tr>\n");
      out.write("    </table>\n");
      out.write("    <input type=\"submit\" value=\"Buscar\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<p>\n");
      out.write("    <table border=\"1\">\n");
      out.write("        <tr>\n");
      out.write("        <th>Ingreso</th><th>Salida</th><th>Placa</th><th>Clientes</th><th>Codigo de Barras</th>\n");
      out.write("        <th><a href=\"principal.jsp?CONTENIDO=parqueo/ingresoVehiculo.jsp&idParqueadero=");
      out.print(parqueadero.getId() );
      out.write("\" title=\"Ingreso vehiculo\">+</a></th>\n");
      out.write("        </tr>\n");
      out.write("        ");
      out.print(lista);
      out.write("\n");
      out.write("    </table>\n");
      out.write("</p>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
